# # Reference:
# # https://docs.gitlab.com/omnibus/installation/index.html
# # https://about.gitlab.com/install/#ubuntu
# # https://docs.gitlab.com/ee/topics/offline/quick_start_guide.html -> offline gitlab installation

# FROM ubuntu:22.04

# # Install and configure the necessary dependencies
# RUN apt-get update && \
# DEBIAN_FRONTEND=noninteractive apt-get install -yq curl openssh-server ca-certificates tzdata perl

# # Postfix (or Sendmail) to send notification emails. If you want to use another solution to send emails please skip this step
# RUN apt-get install -y postfix

# # Add the GitLab package repository and install the package
# RUN curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | bash


# # Do not run EXTERNAL_URL="https://gitlab.example.com" apt-get install gitlab-ee on docker container.
# # This will occur ruby_block[wait for logrotate service socket] action run error.
# RUN apt-get install gitlab-ee
# # GitLab was unable to detect a valid hostname for your instance.
# # Please configure a URL for your GitLab instance by setting `external_url`                                               configuration in /etc/gitlab/gitlab.rb file.                                                                            Then, you can start your GitLab instance by running the following command:
# # gitlab-ctl reconfigure


# use ubuntu to install gitlab will occur ruby_block[wait for logrotate service socket] action run error anyway.
# So I use gitlab/gitlab-ee:latest to instead and it work and go through smoothly.

FROM gitlab/gitlab-ee:latest


# install gitlab runner for CICD
RUN curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | bash
RUN apt-get install -y gitlab-runner


# Only for WSL install docker executor
RUN curl https:/get.docker.com | sh